---
- name: Install httpd
  hosts: all
  gather_facts: no
  strategy: free
  tasks:
    - name: Install htpd
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        state: started