---
- hosts: centos.vmware
  gather_facts: false
  tasks:
    - name: Check if git is installed
      shell: rpm -q git
      register: check_if_git_installed
      ignore_errors: true

    - name: Debug git check result
      debug: var=check_if_git_installed

    - name: Write message if git is missing
      shell: echo "Oops, git is missing" > is_git_installed.txt
      when: check_if_git_installed.rc != 0

    - name: Write git version if git is installed
      shell: git --version > is_git_installed.txt
      when: check_if_git_installed.rc == 0
