---
- hosts: web2
  gather_facts: no
  tasks:
    - name: install nginx
      apt: name=nginx state=present
      tags: [install_core]

    - name: install extra packages
      apt: name={{item}}
      with_items: "{{extra_packages}}"
      when: extra_packages is defined and extra_packages == "htop"