---
- name: Install httpd
  hosts: web1
  gather_facts: no
  tasks:
    block:
      - name: Install httpd
        yum:
          name: httpd
          state: present

      - name: Do not remove this task
        command: /bin/false
        register: results

      - shell: "echo {{ results.msg }} > /tmp/output"
      
      - name: start service
        service:
          name: httpd
          state: started
    ignore_errors: yes