---
  - hosts: node01
    become: true
    tasks:
      - name: copy a file in node01
        copy:
          src: /usr/src/blog/index.html
          dest: /opt/blog/index.html
          remote_src: yes

  - hosts: node02
    become: true
    tasks:
      - name: copy a fil ein node02
        copy:
          src: /usr/src/blog/index.html
          dest: /opt/blog/index.html
          remote_src: yes
