---
  - name: store ansible facts into a file
    hosts: web1
    tasks:
      - name: debug facts
        debug: ansible_facts

      - name: copy ansible facts into file
        copy:
          content: {{ ansible_facts }}
          dest: /home/thor/playbooks/web/web-facts.txt