---
  - name: store ansible facts into a file
    hosts: web1
    become: true
    tasks:
      - name: debug facts
        debug: 
          var: ansible_facts

      - name: copy ansible facts into file
        copy:
          content: "{{ ansible_facts }}"
          dest: /home/thor/playbooks/web/web-facts.txt