---
  - name: create a file with content
    hosts: node01
    become: true
    tasks:
      - name: using file module
        copy:
          dest: /opt/file.txt
          content: This file is created by Ansible!