---
  - name: create a file with content
    hosts: node01
    tasks:
      - name: using file module
        file:
          path: /opt/file.txt
          state: file
          content: This file is created by Ansible!