---
  - name: Create an empty file in node01
    hosts: node01
    become: yes
    tasks:
      - name: create an empty file
        command:  touch /opt/news/blog.txt && chgrp sam /opt/news/blog.txt
    
  - name: create an empty file in node02  
    hosts: node02
    become: yes
    tasks:
      - name: create another empty file and change its group
        file:
          path: /opt/news/story.txt
          command: touch
          owner: sam