---
  - hosts: node01
    become: true
    tasks:
      - replace: 
          path: /opt/music/blog.txt
          regexp: 'Kodekloud'
          replace: 'Ansilbe'

  - hosts: node02
    become: true
    tasks:
      - replace:
