---
- name: help me fix it playbook
  hosts: centos.vmware
  gather_facts: no
  tasks:
    - name: alternative way to gather facts about remote host
      setup: filter='ansible_dist*'
      register: facts
      
    - debug: 
      var: facts

    # - shell: echo "{{facts.ansible_distribution}}" > output.txt