---
- name: Create and manage facts file using blockinfile
  hosts: node02
  gather_facts: yes  # Enable fact gathering
  tasks:
    - name: Create a facts.txt file with system information
      blockinfile:
        path: /root/facts.txt
        block: |
          This is Ansible managed node {{ ansible_hostname }}
          IP address of host is {{ ansible_default_ipv4.address }}
          Its OS family is {{ ansible_os_family }}
  
    - name: Copy facts.txt to /usr/share/nginx/html as index.html
      copy:
        src: /root/facts.txt
        dest: /usr/share/nginx/html/index.html
