---
- name: start firewall
  hosts: centos.vmware
  become: yes
  tasks:
  - name: make sure firewalld is installed
    yum:
     name: firewalld
     state: installed
  - name: start firewall
    service:
     name: firewalld
     state: started