---
  - name: installing httpd package on centos machine
    hosts: web1
    become: yes
    tasks:
      - name: Install epel-release
        yum: 
          name: epel-release
          state: present

      - name: install httpd package
        yum: 
          name: httpd
          state: installed