---
- name: create user with ssh key
  hosts: all 
  tasks:
    - name: create a user
      user:
        name: deploy

    - name: copy authorized keys to all nodes for deploy user
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '~/playbooks/devops.pub') }}"