---
-  name: 'Print list of fruits'
   hosts: localhost
   vars:
     fruits:
       - Apple
       - Banana
       - Grapes
       - Orange
   tasks:
     with_items:
     - Apple
     - Banana
     - Grapes
     - Orange
     - command: 'echo "{{ item }}"'