---
- name: 'Install required packages'
  hosts: localhost
  become: yes
  tasks:
    - yum:
        name: "{{ items }}"
        state: present
        with_items:
          - httpd
          - make
          - vim