---
- name: 'Install required packages'
  hosts: localhost
  become: yes
  tasks:
    - yum:
        name: '{{ item }}'
        state: present
        with_items:
          - httpd
          - make
          - vim