---
  - name: 'Install required packages'
    hosts: localhost
    become: yes
    vars:
      packages:
        - httpd
        - make
        - vim
    tasks:
      - apt:
          name: {{ packages.item }}
          state: present