- hosts: localhost
  connection: local
  vars:
    dialogue: "The name is Bourne, James Bourne!"
  tasks:
    - name: Generate name file
      template:
        src: name.txt.j2
        dest: /tmp/name.txt