--- 
- name: unarchive and delete srd
  hosts: web1
  tasks:
    - unarchive:
        src: /root/data.tar.gz
        dest: /srv
        remote_src: yes
    - file: 
        path: /root/data.tar.gz
        state: absent
    
      