- name: Deploy lamp stack application
  hosts: centos.vmware
  become: yes
  tasks:
    - name: Install common dependencies
      yum:
        name:
          - python3-libselinux
          - python3-libsemanage
          - firewalld
          - mariadb-server
          - MySQL-python

          # old package
          # - libselinux-python
          # - libsemanage-python
          # - firewalld
        state: installed

    - name: copy files/my.cnf to /etc/my.cnf
      copy:
        src: files/my.cnf
        dest: /etc/my.cnf

