- name: Deploy lamp stack application
  hosts: centos.vmware
  become: yes
  tasks:
    - name: Install common dependencies
      yum:
        name:
          - python3-libselinux
          - python3-libsemanage
          - firewalld

- name: Deploy lamp stack application
  hosts: centos.vmware
  become: yes
  tasks:
    - name: yum install packages
      yum: 
        name:
          - mariadb-server
          - python3-PyMySQL
        state: installed

    - name: copy files/my.cnf to /etc/my.cnf
      copy:
        src: files/my.cnf
        dest: /etc/my.cnf

    - name: enable services
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: allow firewalld for MySQL-python
      firewalld:
        port: "{{ mysql_port }}/tcp"
        zone: public
        state: enabled
        immediate: yes
        permanent: yes

- name: Configure database
  hosts: centos.vmware
  become: yes
  vars:
    mysql_root_password: 3242135khdbpasswordroot
    mysql_dbname: ecomdb
    mysql_user: ecomuser
    mysql_password: ecomuser
  
  tasks:
    - name: Create the database
      mysql_db:
        name: "{{ mysql_dbname }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a new user and grant privileges
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_dbname }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: copy db-load-script.sql and load it
      copy:
        src: files/db-load-script.sql
        dest: /tmp/db-load-script.sql

    - name: load inventory data
      shell: mysql -f < /tmp/db-load-script.sql

- name: configure web server and index.php
  hosts: centos.vmware
  become: yes
  tasks:
    - name: httpd (apache)
      yum: 
        name:
          - httpd
          - php
          - php-mysql
        state: present

    - name: install git
      yum: 
        name:
          - git
        state: installed

    - name: configure firewall for httpd
      firewalld:
        port: "{{ httpd_port }}/tcp"
        zone: public
        immediate: yes
        permanent: yes
    
    - name: replace index.html to index.php in DirectoryIndex
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp : DirectoryIndex index.html
        replace: DirectoryIndex index.php
    
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy the code from repository
      git: 
        repo: "{{ repository }}" 
        dest: /var/www/html/  
        force: yes

    - name: Creates the index.php file
      copy: 
        src: files/index.php 
        dest: /var/www/html/index.php