---
- hosts: all
  become: yes
  tasks:
    - name: Set up user
      user:
        name: "{{ user_details['username'] }}"
        password: "{{ user_details['secret_pass'] }}"
        comment: "{{ user_details['admin@example.com'] }}"
        state: present