- name: Update web server configuration
  hosts: webservers
  tasks:
    - name: Copy web server configuration file
      copy:
        src: /path/to/webserver.conf
        dest: /etc/webserver/webserver.conf
      notify: Restart web server

  handlers:
    - name: Restart web server
      service:
        name: webserver
        state: restarted