name: Exploring Variables and Secrets

on:
  push

env:
    CONTAINER_REGISTERY: docker.io
    DOCKER_USERNAME: khaleelorg
    IMAGE_NAME: nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull NGINX Image
        run: docker pull nginx:latest

      - name: Tag Image for Push
        run: docker tag nginx:latest $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest
