apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-web-app-cluster
  region: eu-central-1
  version: "1.30"

vpc:
  cidr: "10.100.0.0/16"
  subnets:
    public:
      eu-central-1a: { cidr: "10.100.0.0/19" }
      eu-central-1b: { cidr: "10.100.32.0/19" }

managedNodeGroups:
  - name: public-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: false  # Public IPs for node access
    subnets:
      - eu-central-1a
      - eu-central-1b

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

