---
- name: Deploy lamp stack application
  hosts: all
  become: yes

# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: yes
  tasks:
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/db.yml

- name: Deploy lamp stack application
  hosts: lampweb
  become: yes
  tasks:
    - include_tasks: tasks/web.yml