---
- name: install httpd web server and start its service
  hosts: all 
  tasks: 
    - name: install httpd 
      block:
      - package: 
          name: httpd
          state: present

      - service: 
          name: httpd
          state: restarted