name: My First Workflow

on: [push,fork]

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Read Dockerfile
              run: |
                    echo "My first Github Actions Job"
                    ls -ltra
                    cat Dockerfile

            - name: Genereate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            
            # - name: List files
            #   run: ls

            # - name: Read files
            #   run: cat Dockerfile